# Generated by Django 3.2.13 on 2024-05-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
